// Copied from https://github.com/teavver/sc2-salt-visualizer/blob/main/notes/salt.md
// Thanks teavver & gmr!

export const LOOKUP = {
  // Structures
  0: {
    0: "Armory",
    1: "Barracks",
    2: "Bunker",
    3: "Command Center",
    4: "Engineering Bay",
    5: "Factory",
    6: "Fusion Core",
    7: "Ghost Academy",
    8: "Missile Turret",
    9: "Reactor (Barracks)",
    10: "Reactor (Factory)",
    11: "Reactor (Starport)",
    12: "Refinery",
    13: "Sensor Tower",
    14: "Starport",
    15: "Supply Depot",
    16: "Tech Lab (Barracks)",
    17: "Tech Lab (Factory)",
    18: "Tech Lab (Starport)",
    19: "Assimilator",
    20: "Cybernetics Core",
    21: "Dark Shrine",
    22: "Fleet Beacon",
    24: "Gateway",
    25: "Nexus",
    26: "Photon Canon",
    27: "Pylon",
    28: "Robotics Bay",
    29: "Robotics Facility",
    30: "Stargate",
    31: "Templar Archives",
    32: "Twilight Council",
    33: "Baneling Nest",
    34: "Evolution Chamber",
    35: "Extractor",
    36: "Hatchery",
    37: "Hydralisk Den",
    38: "Infestation Pit",
    39: "Nydus Network",
    40: "Roach Warren",
    41: "Spawning Pool",
    42: "Spine Crawler",
    43: "Spire",
    44: "Spore Crawler",
    45: "Ultralisk Cavern",
    46: "Creep Tumor",
  },
  // Units
  1: {

    0: "Banshee",
    1: "Battlecruiser",
    2: "Ghost",
    3: "Hellion",
    4: "Marauder",
    5: "Marine",
    6: "Medivac",
    7: "Raven",
    8: "Reaper",
    9: "SCV",
    10: "Siege Tank",
    11: "Thor",
    12: "Viking",
    13: "Archon",
    14: "Carrier",
    15: "Colossus",
    16: "Dark Templar",
    17: "High Templar",
    18: "Immortal",
    19: "Mothership",
    20: "Observer",
    21: "Phoenix",
    22: "Probe",
    23: "Sentry",
    24: "Stalker",
    25: "Void Ray",
    26: "Zealot",
    27: "Corruptor",
    28: "Drone",
    29: "Hydralisk",
    30: "Mutalisk",
    31: "Overlord",
    32: "Queen",
    33: "Roach",
    34: "Ultralisk",
    35: "Zergling",
    38: "Infestor",
    39: "Warp Prism",
    40: "Battle Hellion",
    41: "Warhound",
    42: "Widow Mine",
    43: "Mothership Core",
    44: "Oracle",
    45: "Tempest",
    46: "Swarm Host",
    47: "Viper",
  },
  // Morphs
  2: {
    0: "Orbital Command",
    1: "Planetary Fortress",
    2: "Warp Gate",
    3: "Lair",
    4: "Hive",
    5: "Greater Spire",
    6: "Brood Lord",
    7: "Baneling",
    8: "Overseer",

  },
  // Upgrades
  3: {
    0: "Terran Building Armor",
    1: "Terran Infantry Armor",
    2: "Terran Infantry Weapons",
    3: "Terran Ship Plating",
    4: "Terran Ship Weapons",
    5: "Terran Vehicle Plating",
    6: "Terran Vehicle Weapons",
    7: "250mm Strike Cannons",
    8: "Banshee - Cloaking",
    9: "Ghost - Cloaking",
    10: "Hellion - Pre-igniter",
    11: "Marine - Stimpack",
    12: "Raven - Seeker Missiles",
    13: "Siege Tank - Siege Tech",
    14: "Bunker - Neosteel Frame",
    15: "Marauder - Concussive Shells",
    16: "Marine - Combat Shields",
    17: "Reaper Speed",
    18: "Protoss Ground Armor",
    19: "Protoss Ground Weapons",
    20: "Protoss Air Armor",
    21: "Protoss Air Weapons",
    22: "Protoss Shields",
    23: "Sentry - Hallucination",
    24: "High Templar - Psi Storm",
    25: "Stalker - Blink",
    26: "Warp Gate Tech",
    27: "Zealot - Charge",
    28: "Zerg Ground Carapace",
    29: "Zerg Melee Weapons",
    30: "Zerg Flyer Carapace",
    31: "Zerg Flyer Weapons",
    32: "Zerg Missile Weapons",
    33: "Hydralisk - Grooved Spines",
    34: "Overlord - Pneumatized Carapace",
    35: "Overlord - Ventral Sacs",
    36: "Roach - Glial Reconstitution",
    37: "(REMOVED FROM GAME) Roach - Organic Carapace",
    38: "Roach - Tunneling Claws",
    39: "(REMOVED FROM GAME) Ultralisk - Anabolic Synthesis",
    40: "Ultralisk - Chitinous Plating",
    41: "Zergling - Adrenal Glands",
    42: "Zergling - Metabolic Boost",
    43: "(REMOVED FROM GAME) Zergling - Obverse Incubation",
    44: "Burrow",
    45: "Centrifugal Hooks",
    46: "Ghost - Moebius Reactor",
    47: "Extended Thermal Lance",
    48: "(REMOVED FROM GAME) Khaydarin Amulet",
    49: "Neural Parasite",
    50: "Pathogen Gland",
    51: "Battlecruiser - Behemoth Reactor",
    52: "Battlecruiser - Weapon Refit",
    53: "Hi-Sec Auto Tracking",
    54: "Medivac - Caduceus Reactor",
    55: "Raven - Corvid Reactor",
    56: "Raven - Durable Materials",
    57: "Hellion - Transformation servos",
    58: "Carrier - Graviton Catapult",
    59: "Observer - Gravatic Boosters",
    60: "Warp Prrism - Gravatic Drive",
    61: "Oracle - Bosonic Core",
    62: "Tempest - Gravity Sling",
    63: "Ultralisk - Evolve Burrow Charge",
    64: "Swarm Host - Evolve Enduring Locusts",
    65: "Hydralisk - Muscular Augments",
    66: "Drilling claws",
    67: "Anion Pulse-Crystals",
  },
};
